# Numpy

The NumPy library is the core library for scientific computing in Python. It provides a high-performance multidimensional array object, and tools for working with these arrays.

In [35]:
#firstly import numpy
import numpy as np

## Creating array

In [44]:
a=np.array([5,7,20])
print(a)
print(repr(a))          #repr__() method returns the object's printable representation in the form of a string.
print(str(a))

[ 5  7 20]
array([ 5,  7, 20])
[ 5  7 20]


In [47]:
b = np.array([(4.5,10,20), (4,5,6)], dtype = float)
print(b)

[[ 4.5 10.  20. ]
 [ 4.   5.   6. ]]


In [52]:
c=np.array([[(5.5,3,7) , (4,8,12)],[(5,10,15),(2,4,6)]] ,dtype = float)
print(c)

[[[ 5.5  3.   7. ]
  [ 4.   8.  12. ]]

 [[ 5.  10.  15. ]
  [ 2.   4.   6. ]]]


## Initial Placeholders

In [58]:
#create an array with zeros
np.zeros((3,4), dtype=np.int16)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]], dtype=int16)

In [60]:
#create an array ones----np.array(kitna array chahiye, rows,column)
np.ones((2,3,6), dtype = int)

array([[[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]],

       [[1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1]]])

In [65]:
# Create an array of evenly spaced values (step value) 
d=np.arange(2,50,5)           #np.arange(start,end,gap/step)
print(d)

[ 2  7 12 17 22 27 32 37 42 47]


linspace is an in-built function in Python's NumPy library. It is used to create an evenly spaced sequence in a specified interval.

In [72]:
#Create an array of evenly spaced values (number of samples)
np.linspace(2,10,5)        #np.linspace(start,end,no_of_samples)

array([ 2.,  4.,  6.,  8., 10.])

In [76]:
# Create a constant array
e=np.full((2,2),4)   #np.full((shape_of_array),values)
print(e)

[[4 4]
 [4 4]]


In [82]:
#Create a 4*4 identity matrix

#Four-dimensional array having the value of 1 in the diagonal section in the matrix and 0 placed at values in all other elements 
#in the matrix
f=np.eye(4)
print(f)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [86]:
#Create an array with random values
np.random.random((3,3))

array([[0.38990852, 0.65329909, 0.23816306],
       [0.07383913, 0.58825326, 0.30440874],
       [0.09095716, 0.74556767, 0.46867958]])

In [88]:
#Create an empty array
np.empty((3,2))

array([[ 4.5, 10. ],
       [20. ,  4. ],
       [ 5. ,  6. ]])

In [94]:
 #Create an empty array
np.empty((2,2))

array([[1., 1.],
       [1., 1.]])

## Data Type

In [95]:
np.int64   #Signed 64-bit integer types
np.float32 #Standard double-precision floating point
np.complex #Complex numbers represented by 128 floats
np.bool    #Boolean type storing TRUE and FALSE values
np.object  #Python object type
np.string_ #Fixed-length string type
np.unicode_ #Fixed-length unicode type

<ipython-input-95-7e466903aa03>:3: DeprecationWarning: `np.complex` is a deprecated alias for the builtin `complex`. To silence this warning, use `complex` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.complex128` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.complex #Complex numbers represented by 128 floats
<ipython-input-95-7e466903aa03>:4: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.bool    #Boolean type storing TRUE and FALSE values
<ipython-input-95-7e466903aa03>:5: DeprecationWarning: `np.object

numpy.str_

## Inspecting of array

In [103]:
a=np.array([2,4,6,8,10])

a.shape            # array dimensions


(5,)

In [105]:
len(a)              #length of array

5

In [106]:
a.ndim              #dimensions

1

In [107]:
a.size             #size of array

5

In [108]:
a.dtype              #type of array element

dtype('int32')

In [109]:
a.dtype.name         #Name of data type

'int32'

In [113]:
a.astype(float)        #convest data element

array([ 2.,  4.,  6.,  8., 10.])

## Arithmetic operations

In [120]:
a=np.array([10,20,30])
b=np.array([[2,4,6],[1,2,3.]])

In [127]:
#addition
# c=a+b
# print(c)
np.add(a,b)  #one line

array([[12., 24., 36.],
       [11., 22., 33.]])

In [126]:
#subtraction
# d=a-b
# print(d)
np.subtract(a,b)  #Subtraction

array([[ 8., 16., 24.],
       [ 9., 18., 27.]])

In [133]:
#multipication
# e=a*b
# print(e)
np.multiply(a,b)

array([[ 20.,  80., 180.],
       [ 10.,  40.,  90.]])

In [132]:
#division
# f=a/b
# print(f)
np.divide(a,b) #Division

array([[ 5.,  5.,  5.],
       [10., 10., 10.]])

In [138]:
a+b

array([[12., 24., 36.],
       [11., 22., 33.]])

In [137]:
a-b

array([[ 8., 16., 24.],
       [ 9., 18., 27.]])

In [139]:
a*b

array([[ 20.,  80., 180.],
       [ 10.,  40.,  90.]])

In [140]:
a/b

array([[ 5.,  5.,  5.],
       [10., 10., 10.]])

In [142]:
np.exp(b) , #exp function

array([[  7.3890561 ,  54.59815003, 403.42879349],
       [  2.71828183,   7.3890561 ,  20.08553692]])

In [143]:
np.sqrt(b) #Square root

array([[1.41421356, 2.        , 2.44948974],
       [1.        , 1.41421356, 1.73205081]])

In [146]:
np.log(b) #Element-wise natural logarithm

array([[0.69314718, 1.38629436, 1.79175947],
       [0.        , 0.69314718, 1.09861229]])

In [145]:
np.sin(b) #Print sines of an array

array([[ 0.90929743, -0.7568025 , -0.2794155 ],
       [ 0.84147098,  0.90929743,  0.14112001]])

In [155]:
x=np.array([1,2,3])
y=np.array([4,5,6])
z=x+y
e.dot(z) #Dot product Must have same shape

array([2280., 1140.])

## Comparison

In [161]:
a=np.array([1,2,4])
b=np.array([[1,2,3],[4,5,6]])
a == b                                     #Element-wise comparison

array([[ True,  True, False],
       [False, False, False]])

In [162]:
a < 2    #Element-wise comparison

array([ True, False, False])

In [163]:
np.array_equal(a, b) #Array-wise comparison

False

## Aggregate function

In [164]:
a.sum() #Array-wise sum

7

In [167]:
b.max()               #Array-wise maximum value

6

In [168]:
b.min()             #Array-wise minimum value

1

In [175]:
a.max(axis=0)                                #Maximum value of an array row

4

In [179]:
b.min(axis=0)                             #Minmum value of an array row

array([1, 2, 3])

In [180]:
b.cumsum(axis=1)                           #Cumulative sum of the elements

array([[ 1,  3,  6],
       [ 4,  9, 15]], dtype=int32)

In [181]:
a.mean() #Mean

2.3333333333333335

In [182]:
np.median(b)                           #Median

3.5

In [183]:
np.corrcoef(a)                  #Correlation coefficient

1.0

In [184]:
np.std(b)                      #Standard deviation

1.707825127659933

## Copying Array

In [185]:
h = a.view()                #Create a view of the array with the same data
h=a.view()

In [186]:
np.copy(a)                #Create a copy of the array


array([1, 2, 4])

In [187]:
h = a.copy()                         #Create a deep copy of the array

## Sorting Arrays

In [199]:
x=np.array([[1,2,5],[3,7,4]])

x.sort()                                      #Sort an array

In [200]:
x

array([[1, 2, 5],
       [3, 4, 7]])

In [196]:
x.sort(axis=0)                                    #Sort the elements of an array's axis

In [197]:
x

array([1, 2, 3, 4, 5, 7])

## Subsetting/Modifying

In [202]:
a[2]                                  # Select the element at the 2nd index 3

4

In [205]:
# accessing the element
b[1,2]                                   #Select the element at row 1 column 2 (equivalent to b[1][2])

6

In [204]:
b

array([[1, 2, 3],
       [4, 5, 6]])

## Slicing 

In [207]:
x[0:2]                                             #Select items at index 0 and 1

array([[1, 2, 5],
       [3, 4, 7]])

In [208]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [210]:
b[0:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [209]:
b[0:2,1]                                            #Select items at rows 0 and 1 in column 1

array([2, 5])

In [211]:
b[:1]                                       #Select all items at row 0 (equivalent to b[0:1, :])

array([[1, 2, 3]])

In [212]:
a

array([1, 2, 4])

In [213]:
a[ : :-1]                                    #Reversed array a array([4, 2, 1])

array([4, 2, 1])

In [214]:
b[::-1]

array([[4, 5, 6],
       [1, 2, 3]])

## Boolean Indexing

In [215]:
a

array([1, 2, 4])

In [218]:
a[a<4]                                   #Select elements from a less than 4

array([1, 2])

## Fancy Indexing

In [220]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [219]:
b[[1, 0, 1, 0],[0, 1, 2, 0]]                 #Select elements (1,0),(0,1),(1,2) and (0,0)

array([4, 2, 6, 1])

In [221]:
b[[1, 0, 1, 0]][:,[0,1,2,0]]                     #Select a subset of the matrix’s rows and columns

array([[4, 5, 6, 4],
       [1, 2, 3, 1],
       [4, 5, 6, 4],
       [1, 2, 3, 1]])

## Transposing Array

In [222]:
i = np.transpose(b)                          #Permute array dimensions

In [224]:
i.T                                         #Permute array dimensions

array([[1, 2, 3],
       [4, 5, 6]])

## Changing Array Shape

In [227]:
b.ravel()                                           #Flatten the array

array([1, 2, 3, 4, 5, 6])

In [229]:
z.reshape(3,-2)                                #Reshape, but don’t change data

array([[5],
       [7],
       [9]])

## Adding/Removing Elements

In [230]:
h.resize((2,6))              #Return a new array with shape (2,6)

In [231]:
h

array([[1, 2, 4, 0, 0, 0],
       [0, 0, 0, 0, 0, 0]])

In [233]:
np.append(h,c)                               #Append items to an array

array([1., 2., 4., 0., 0., 0., 0., 0., 0., 0., 0., 0., 2., 4., 6., 1., 2.,
       3.])

In [234]:
np.insert(a, 1, 5)                            #Insert items in an array

array([1, 5, 2, 4])

In [235]:
np.delete(a,[1])                              #Delete items from an array

array([1, 4])

## Combining Arrays

In [242]:
np.concatenate((x,b),axis=0)                     #Concatenate arrays

array([[1, 2, 5],
       [3, 4, 7],
       [1, 2, 3],
       [4, 5, 6]])

In [244]:
a

array([1, 2, 4])

In [245]:
b

array([[1, 2, 3],
       [4, 5, 6]])

In [246]:
np.vstack((a,b))                               #Stack arrays vertically (row-wise)

array([[1, 2, 4],
       [1, 2, 3],
       [4, 5, 6]])

In [248]:
e

array([[ 20.,  80., 180.],
       [ 10.,  40.,  90.]])

In [249]:
f

array([[ 5.,  5.,  5.],
       [10., 10., 10.]])

In [247]:
np.r_[e,f]                                               #Stack arrays vertically (row-wise)

array([[ 20.,  80., 180.],
       [ 10.,  40.,  90.],
       [  5.,   5.,   5.],
       [ 10.,  10.,  10.]])

In [250]:
np.hstack((e,f))                                        #Stack arrays horizontally (column-wise)

array([[ 20.,  80., 180.,   5.,   5.,   5.],
       [ 10.,  40.,  90.,  10.,  10.,  10.]])

In [251]:
np.column_stack((e,f))                                 #Create stacked column-wise arrays

array([[ 20.,  80., 180.,   5.,   5.,   5.],
       [ 10.,  40.,  90.,  10.,  10.,  10.]])

In [253]:
np.c_[e,f]                                  #Create stacked column-wise arrays

array([[ 20.,  80., 180.,   5.,   5.,   5.],
       [ 10.,  40.,  90.,  10.,  10.,  10.]])

## Splitting Arrays

In [254]:
np.hsplit(a,3)               #Split the array horizontally at the 3rd index

[array([1]), array([2]), array([4])]

In [255]:
np.vsplit(c,2)               #Split the array vertically at the 2nd index

[array([[2., 4., 6.]]), array([[1., 2., 3.]])]

# The End